version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/codedeploy-temp
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/deploy_staging.sh
      runas: testcase  # Staging user
      timeout: 300

  BeforeInstall:
    - location: scripts/wait_for_approval.sh
      runas: root
      timeout: 300

  ApplicationStart:
    - location: scripts/deploy_production.sh
      runas: etpmc  # Production user
      timeout: 300
